### PR TITLE
Don’t put DLLs in eager_resources

### PR DESCRIPTION
**Pull request by rolyp**

### CODE REVIEW

**Comment by inakleinbottle** [comment]
DLL's as eager resource was the way that we fixed the problems getting libiomp5.dll and recombine.dll into the Windows distribution. I don't think there is a better solution. What is the reason it is not appropriate?

**Comment by rolyp** [comment]
I was just going by the documentation (
https://setuptools.readthedocs.io/en/latest/userguide/miscellaneous.html)
which suggests it isn’t needed for DLLs. If we need it, though, then I
guess we need it – unfortunately we’re lacking a test that shows that we
do. (There are probably several reasons now why we need installer-level
tests..)

**Comment by terrylyons** [comment]
I thought we avoided this issue by using the package that looks for external dlls etc and repackages them into the wheel for us.  On Linux, auditwheel.

Terry

On 25 Feb 2021, at 22:06, Roly Perera <notifications@github.com> wrote:

﻿

I was just going by the documentation (
https://setuptools.readthedocs.io/en/latest/userguide/miscellaneous.html)
which suggests it isn’t needed for DLLs. If we need it, though, then I
guess we need it – unfortunately we’re lacking a test that shows that we
do. (There are probably several reasons now why we need installer-level
tests..)

**Comment by inakleinbottle** [comment]
@terrylyons Adding the DLLs to eager resources was a Windows only fix. If you recall, we had problems where these libraries were not added to the wheel and the tests did not detect this because the testing environment was using the system package used to build.

**Pull request merged**
